---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "scheduledjob-git-sync"
  annotations:
    description: "Scheduled Task to Perform Git Repo Synchronization"
    iconClass: "icon-shadowman"
    tags: "management,scheduledjob,git,sync"
objects:
- kind: Secret
  metadata:
    name: ssh-key-secret
  type: Opaque
  data:
    ssh-privatekey: ${GIT_SYNC_PRIVATE_KEY} 
    ssh-publickey: ${GIT_SYNC_PUBLIC_KEY} 
- kind: "ScheduledJob"
  apiVersion: "batch/v2alpha1"
  metadata:
    name: "${JOB_NAME}"
    labels:
      template: "scheduledjob-git-sync"
  spec:
    schedule: "${SCHEDULE}"
    concurrencyPolicy: "Forbid"
    successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
    failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
    jobTemplate:
      spec:
        template:
          spec:
           volumes:
            - name: secret-volume
              secret:
                secretName: ssh-key-secret
           containers:
              - name: "${JOB_NAME}"
                image: "openshift3/jenkins-slave-base-rhel7"
                command:
                  - "/bin/bash"
                  - "-c"
                  - "git clone ${GIT_URL} && git pull --all && git remote add backup ${GIT_SYNC_URL} && git push --all backup && echo Finished syncing"
                volumeMounts:
                - name: secret-volume
                  readOnly: true
                  mountPath: "/etc/secret-volume"
            restartPolicy: "Never"
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 500
            dnsPolicy: "ClusterFirst"
parameters:
  - name: "JOB_NAME"
    displayName: "Job Name"
    description: "Name of the Scheduled Job to Create."
    value: "scheduledjob-git-sync"
    required: true
  - name: "SCHEDULE"
    displayName: "Cron Schedule"
    description: "Cron Schedule to Execute the Job"
    value: "@hourly"
    required: true
  - name: "JOB_SERVICE_ACCOUNT"
    displayName: "Service Account Name"
    description: "Name of the Service Account To Exeucte the Job As."
    value: "git-syncer"
    required: true
  - name: "KEEP_COMPLETE"
    displayName: "Number of Completed Items"
    description: "Number of completed items that will not be considered for pruning."
    value: "5"
    required: true
  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    displayName: "Successful Job History Limit"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true
  - name: "FAILED_JOBS_HISTORY_LIMIT"
    displayName: "Failed Job History Limit"
    description: "The number of failed jobs that will be retained"
    value: "5"
    required: true
  - name: "GIT_URL"
    displayName: "Git Server URL"
    description: "URL of you Git server"
    required: true
  - name: "GIT_SYNC_URL"
    displayName: "Git Server URL to be synced to"
    description: "URL of you Git server to be synced to"
    required: true
  - name: "GIT_SYNC_PRIVATE_KEY"
    displayName: "ssh private key for the Server to be synced to"
    description: "ssh private key for the Git server to be synced to"
    required: true
  - name: "GIT_SYNC_PUBLIC_KEY"
    displayName: "ssh public key for the Server to be synced to"
    description: "ssh public key for the Git server to be synced to"
    required: true
labels:
  template: "scheduledjob-git-sync"
