---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "scheduledjob-git-sync"
  annotations:
    description: "Scheduled Task to Perform Git Repo Synchronization"
    iconClass: "icon-shadowman"
    tags: "management,scheduledjob,git,sync"
objects:
- kind: Secret
  apiVersion: "v1"
  metadata:
    name: ssh-key-secret
  type: Opaque
  data:
    ssh-privatekey: ${GIT_SYNC_PRIVATE_KEY} 
- kind: "ScheduledJob"
  apiVersion: "batch/v2alpha1"
  metadata:
    name: "${JOB_NAME}"
    labels:
      template: "scheduledjob-git-sync"
  spec:
    schedule: "${SCHEDULE}"
    concurrencyPolicy: "Forbid"
    successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
    failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
    jobTemplate:
      spec:
        template:
          spec:
            volumes:
            - name: secret-volume
              secret:
                secretName: ssh-key-secret
            containers:
              - name: "${JOB_NAME}"
                #image: "registry.access.redhat.com/rhel7:latest"
                #image: "registry.access.redhat.com/jboss-eap-7/eap70-openshift"
                image: "openshift3/jenkins-2-rhel7"
                command:
                  - "/bin/bash"
                  - "-c"
                  - "mkdir /tmp/.ssh && echo made dir && printf 'host ${GIT_SYNC_HOST}\n HostName ${GIT_SYNC_HOST}\n IdentityFile /etc/secret-volume/ssh-privatekey\n User git\n' >> /tmp/.ssh/config && echo created cofig && chmod 400 /tmp/.ssh/config && echo completed chmod && ssh-keyscan -p ${GIT_SYNC_PORT} -H ${GIT_SYNC_HOST} >> /tmp/.ssh/known_hosts && echo git sync added to known_hosts && ssh-keyscan -p ${GIT_PORT} -H ${GIT_HOST} >> /tmp/.ssh/known_hosts && echo finished keyscan && export GIT_COMMITTER_NAME=test && export GIT_COMMITTER_EMAIL=pcarney@example.com && echo $GIT_COMMITTER_NAME && echo $GIT_COMMITTER_EMAIL && echo complete export && git clone https://${GIT_HOST}/${GIT_REPO} /tmp/temp && echo finished cloning && cd /tmp/temp && git pull --all && git remote add backup ssh://git@${GIT_SYNC_HOST}:${GIT_SYNC_PORT}/${GIT_SYNC_REPO} && echo added backup && git push --all backup && echo finished"
                volumeMounts:
                - name: secret-volume
                  readOnly: true
                  mountPath: "/etc/secret-volume"
            restartPolicy: "Never"
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 500
            dnsPolicy: "ClusterFirst"
parameters:
  - name: "JOB_NAME"
    displayName: "Job Name"
    description: "Name of the Scheduled Job to Create."
    value: "scheduledjob-git-sync"
    required: true
  - name: "SCHEDULE"
    displayName: "Cron Schedule"
    description: "Cron Schedule to Execute the Job"
    value: "@hourly"
    required: true
  - name: "KEEP_COMPLETE"
    displayName: "Number of Completed Items"
    description: "Number of completed items that will not be considered for pruning."
    value: "5"
    required: true
  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    displayName: "Successful Job History Limit"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true
  - name: "FAILED_JOBS_HISTORY_LIMIT"
    displayName: "Failed Job History Limit"
    description: "The number of failed jobs that will be retained"
    value: "5"
    required: true
  - name: "GIT_HOST"
    displayName: "Git server host name"
    description: "Git server host name"
    required: true
  - name: "GIT_PORT"
    displayName: "Port of the main git server"
    description: "Port of the main git server, NEED TO MAKE SURE THIS MATCHES THE PROTOCOL"
    required: true 
  - name: "GIT_REPO"
    displayName: "Git server repo path"
    description: "Git server repo path, i.e. userName/repo-name.git"
    required: true
  - name: "GIT_SYNC_HOST"
    displayName: "Git backup server host name of the server to be synced to"
    description: "Git backup server host name of the server to be synced to, used to add to known hosts"
    required: true
  - name: "GIT_SYNC_PORT"
    displayName: "Port of the server to be synced to"
    description: "Port of the server to be synced to, used to add to known hosts"
    required: true
    value: "22"
  - name: "GIT_SYNC_REPO"
    displayName: "Git backup server repo path"
    description: "Git backup server repo path, i.e. userName/repo-name.git"
    required: true
  - name: "GIT_SYNC_PRIVATE_KEY"
    displayName: "SSH private key for the Git server to be synced to"
    description: "SSH private key for the Git server to be synced to, NOTE: no passphrase! and should all be on one line without any headings"
    required: true
labels:
  template: "scheduledjob-git-sync"
